/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskRunFromDiscriminatorValue, type TaskRun } from '../../models/index.js';
// @ts-ignore
import { FavoritesRequestBuilderRequestsMetadata, type FavoritesRequestBuilder } from './favorites/index.js';
// @ts-ignore
import { RunItemRequestBuilderNavigationMetadata, type RunItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task/run
 */
export interface RunRequestBuilder extends BaseRequestBuilder<RunRequestBuilder> {
    /**
     * The favorites property
     */
    get favorites(): FavoritesRequestBuilder;
    /**
     * Gets an item from the ApiSdk.task.run.item collection
     * @param id Unique identifier of the item
     * @returns {RunItemRequestBuilder}
     */
     byId(id: string) : RunItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskRun[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskRun[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RunRequestBuilderUriTemplate = "{+baseurl}/task/run";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RunRequestBuilderNavigationMetadata: Record<Exclude<keyof RunRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        navigationMetadata: RunItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    favorites: {
        requestsMetadata: FavoritesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RunRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RunRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskRunFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
