/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ExecuteRequestBuilderRequestsMetadata, type ExecuteRequestBuilder } from './execute/index.js';
// @ts-ignore
import { QueueRequestBuilderRequestsMetadata, type QueueRequestBuilder } from './queue/index.js';
// @ts-ignore
import { RunRequestBuilderRequestsMetadata, type RunRequestBuilder } from './run/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task/{-id}
 */
export interface ItemRequestBuilder extends BaseRequestBuilder<ItemRequestBuilder> {
    /**
     * The execute property
     */
    get execute(): ExecuteRequestBuilder;
    /**
     * The queue property
     */
    get queue(): QueueRequestBuilder;
    /**
     * The run property
     */
    get run(): RunRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ItemRequestBuilderUriTemplate = "{+baseurl}/task/{%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    execute: {
        requestsMetadata: ExecuteRequestBuilderRequestsMetadata,
    },
    queue: {
        requestsMetadata: QueueRequestBuilderRequestsMetadata,
    },
    run: {
        requestsMetadata: RunRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
