/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activity/': RouteRecordInfo<'/activity/', '/activity', Record<never, never>, Record<never, never>>,
    '/tasks/': RouteRecordInfo<'/tasks/', '/tasks', Record<never, never>, Record<never, never>>,
    '/tasks/[taskId]/': RouteRecordInfo<'/tasks/[taskId]/', '/tasks/:taskId', { taskId: ParamValue<true> }, { taskId: ParamValue<false> }>,
    '/tasks/[taskId]/commands/[commandId]': RouteRecordInfo<'/tasks/[taskId]/commands/[commandId]', '/tasks/:taskId/commands/:commandId', { taskId: ParamValue<true>, commandId: ParamValue<true> }, { taskId: ParamValue<false>, commandId: ParamValue<false> }>,
    '/tasks/[taskId]/edit': RouteRecordInfo<'/tasks/[taskId]/edit', '/tasks/:taskId/edit', { taskId: ParamValue<true> }, { taskId: ParamValue<false> }>,
    '/tasks/new': RouteRecordInfo<'/tasks/new', '/tasks/new', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/activity/index.vue': {
      routes: '/activity/'
      views: never
    }
    'src/pages/tasks/index.vue': {
      routes: '/tasks/'
      views: never
    }
    'src/pages/tasks/[taskId]/index.vue': {
      routes: '/tasks/[taskId]/'
      views: never
    }
    'src/pages/tasks/[taskId]/commands/[commandId].vue': {
      routes: '/tasks/[taskId]/commands/[commandId]'
      views: never
    }
    'src/pages/tasks/[taskId]/edit.vue': {
      routes: '/tasks/[taskId]/edit'
      views: never
    }
    'src/pages/tasks/new.vue': {
      routes: '/tasks/new'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
