/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTaskResultItemRequestBuilder, WithTaskResultItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-result/output
 */
export interface OutputRequestBuilder extends BaseRequestBuilder<OutputRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.taskResult.output.item collection
     * @param taskResultId Unique identifier of the item
     * @returns {WithTaskResultItemRequestBuilder}
     */
     byTaskResultId(taskResultId: string) : WithTaskResultItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OutputRequestBuilderUriTemplate = "{+baseurl}/task-result/output";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OutputRequestBuilderNavigationMetadata: Record<Exclude<keyof OutputRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTaskResultId: {
        requestsMetadata: WithTaskResultItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["taskResultId"],
    },
};
/* tslint:enable */
/* eslint-enable */
