/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTaskResultItemRequestBuilder, WithTaskResultItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /tasks/executor
 */
export interface ExecutorRequestBuilder extends BaseRequestBuilder<ExecutorRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.tasks.executor.item collection
     * @param taskResultId Unique identifier of the item
     * @returns {WithTaskResultItemRequestBuilder}
     */
     byTaskResultId(taskResultId: string) : WithTaskResultItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ExecutorRequestBuilderUriTemplate = "{+baseurl}/tasks/executor";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExecutorRequestBuilderNavigationMetadata: Record<Exclude<keyof ExecutorRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTaskResultId: {
        requestsMetadata: WithTaskResultItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["taskResultId"],
    },
};
/* tslint:enable */
/* eslint-enable */
