/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeExecuteTaskRunDto, type ExecuteTaskRunDto } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExecutePostResponse}
 */
// @ts-ignore
export function createExecutePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExecutePostResponse;
}
/**
 * The deserialization information for the current model
 * @param ExecutePostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExecutePostResponse(executePostResponse: Partial<ExecutePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface ExecutePostResponse extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /task/run/{id}/execute
 */
export interface ExecuteRequestBuilder extends BaseRequestBuilder<ExecuteRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExecutePostResponse>}
     */
     post(body: ExecuteTaskRunDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExecutePostResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExecuteTaskRunDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param ExecutePostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExecutePostResponse(writer: SerializationWriter, executePostResponse: Partial<ExecutePostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!executePostResponse || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(executePostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ExecuteRequestBuilderUriTemplate = "{+baseurl}/task/run/{id}/execute";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExecuteRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExecuteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createExecutePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExecuteTaskRunDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
