/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-run/{id}/favorite
 */
export interface FavoriteRequestBuilder extends BaseRequestBuilder<FavoriteRequestBuilder> {
    /**
     * Toggle favorite status of a task run configuration
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     patch(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Toggle favorite status of a task run configuration
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FavoriteRequestBuilderUriTemplate = "{+baseurl}/task-run/{id}/favorite";
/**
 * Metadata for all the requests in the request builder.
 */
export const FavoriteRequestBuilderRequestsMetadata: RequestsMetadata = {
    patch: {
        uriTemplate: FavoriteRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
