/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskResultFromDiscriminatorValue, type TaskResult } from '../../models/index.js';
// @ts-ignore
import { type WithTaskResultItemRequestBuilder, WithTaskResultItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /activity/task-result
 */
export interface TaskResultRequestBuilder extends BaseRequestBuilder<TaskResultRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.activity.taskResult.item collection
     * @param taskResultId Unique identifier of the item
     * @returns {WithTaskResultItemRequestBuilder}
     */
     byTaskResultId(taskResultId: string) : WithTaskResultItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskResult[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskResult[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TaskResultRequestBuilderUriTemplate = "{+baseurl}/activity/task-result";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskResultRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskResultRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTaskResultId: {
        requestsMetadata: WithTaskResultItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["taskResultId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TaskResultRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TaskResultRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
