/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FavoritesRequestBuilderRequestsMetadata, type FavoritesRequestBuilder } from './favorites/index.js';
// @ts-ignore
import { TaskRunItemRequestBuilderNavigationMetadata, type TaskRunItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-run
 */
export interface TaskRunRequestBuilder extends BaseRequestBuilder<TaskRunRequestBuilder> {
    /**
     * The favorites property
     */
    get favorites(): FavoritesRequestBuilder;
    /**
     * Gets an item from the ApiSdk.taskRun.item collection
     * @param id Unique identifier of the item
     * @returns {TaskRunItemRequestBuilder}
     */
     byId(id: string) : TaskRunItemRequestBuilder;
    /**
     * Get all task run configurations
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Get all task run configurations
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TaskRunRequestBuilderUriTemplate = "{+baseurl}/task-run";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskRunRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskRunRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        navigationMetadata: TaskRunItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    favorites: {
        requestsMetadata: FavoritesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TaskRunRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TaskRunRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
