/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskResultOutputFromDiscriminatorValue, type TaskResultOutput } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-result/output/{taskResultId}
 */
export interface WithTaskResultItemRequestBuilder extends BaseRequestBuilder<WithTaskResultItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskResultOutput[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskResultOutput[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTaskResultItemRequestBuilderUriTemplate = "{+baseurl}/task-result/output/{taskResultId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTaskResultItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithTaskResultItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskResultOutputFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
