/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createQueueFromDiscriminatorValue, serializeCreateQueueDto, type CreateQueueDto, type Queue } from '../models/index.js';
// @ts-ignore
import { QueueItemRequestBuilderRequestsMetadata, type QueueItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /queue
 */
export interface QueueRequestBuilder extends BaseRequestBuilder<QueueRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.queue.item collection
     * @param id Unique identifier of the item
     * @returns {QueueItemRequestBuilder}
     */
     byId(id: string) : QueueItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Queue[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Queue[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: CreateQueueDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateQueueDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueueRequestBuilderUriTemplate = "{+baseurl}/queue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QueueRequestBuilderNavigationMetadata: Record<Exclude<keyof QueueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: QueueItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QueueRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QueueRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createQueueFromDiscriminatorValue,
    },
    post: {
        uriTemplate: QueueRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateQueueDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
