/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeExecuteTaskRunDto, type ExecuteTaskRunDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-run/{id}/execute
 */
export interface ExecuteRequestBuilder extends BaseRequestBuilder<ExecuteRequestBuilder> {
    /**
     * Execute a task using a task run configuration
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: ExecuteTaskRunDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Execute a task using a task run configuration
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExecuteTaskRunDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ExecuteRequestBuilderUriTemplate = "{+baseurl}/task-run/{id}/execute";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExecuteRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExecuteRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExecuteTaskRunDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
