/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTaskResultItemRequestBuilder, WithTaskResultItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-result
 */
export interface TaskResultRequestBuilder extends BaseRequestBuilder<TaskResultRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.taskResult.item collection
     * @param taskResultId Unique identifier of the item
     * @returns {WithTaskResultItemRequestBuilder}
     */
     byTaskResultId(taskResultId: string) : WithTaskResultItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TaskResultRequestBuilderUriTemplate = "{+baseurl}/task-result";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskResultRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskResultRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTaskResultId: {
        requestsMetadata: WithTaskResultItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["taskResultId"],
    },
};
/* tslint:enable */
/* eslint-enable */
