/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QueueRequestBuilderRequestsMetadata, type QueueRequestBuilder } from './queue/index.js';
// @ts-ignore
import { TaskResultRequestBuilderNavigationMetadata, TaskResultRequestBuilderRequestsMetadata, type TaskResultRequestBuilder } from './taskResult/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /activity
 */
export interface ActivityRequestBuilder extends BaseRequestBuilder<ActivityRequestBuilder> {
    /**
     * The queue property
     */
    get queue(): QueueRequestBuilder;
    /**
     * The taskResult property
     */
    get taskResult(): TaskResultRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ActivityRequestBuilderUriTemplate = "{+baseurl}/activity";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ActivityRequestBuilderNavigationMetadata: Record<Exclude<keyof ActivityRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    queue: {
        requestsMetadata: QueueRequestBuilderRequestsMetadata,
    },
    taskResult: {
        requestsMetadata: TaskResultRequestBuilderRequestsMetadata,
        navigationMetadata: TaskResultRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
