/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ExecuteRequestBuilderRequestsMetadata, type ExecuteRequestBuilder } from './execute/index.js';
// @ts-ignore
import { FavoriteRequestBuilderRequestsMetadata, type FavoriteRequestBuilder } from './favorite/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task-run/{id}
 */
export interface TaskRunItemRequestBuilder extends BaseRequestBuilder<TaskRunItemRequestBuilder> {
    /**
     * The execute property
     */
    get execute(): ExecuteRequestBuilder;
    /**
     * The favorite property
     */
    get favorite(): FavoriteRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TaskRunItemRequestBuilderUriTemplate = "{+baseurl}/task-run/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskRunItemRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskRunItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    execute: {
        requestsMetadata: ExecuteRequestBuilderRequestsMetadata,
    },
    favorite: {
        requestsMetadata: FavoriteRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
