/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskRunFromDiscriminatorValue, type TaskRun } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task/run/popular
 */
export interface PopularRequestBuilder extends BaseRequestBuilder<PopularRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TaskRun[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TaskRun[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PopularRequestBuilderUriTemplate = "{+baseurl}/task/run/popular";
/**
 * Metadata for all the requests in the request builder.
 */
export const PopularRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PopularRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskRunFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
