/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithNameItemRequestBuilder, WithNameItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task
 */
export interface TaskRequestBuilder extends BaseRequestBuilder<TaskRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.task.item collection
     * @param name Unique identifier of the item
     * @returns {WithNameItemRequestBuilder}
     */
     byName(name: string) : WithNameItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TaskRequestBuilderUriTemplate = "{+baseurl}/task";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byName: {
        navigationMetadata: WithNameItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["name"],
    },
};
/* tslint:enable */
/* eslint-enable */
