/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ItemRequestBuilderNavigationMetadata, type ItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RunRequestBuilderNavigationMetadata, RunRequestBuilderRequestsMetadata, type RunRequestBuilder } from './run/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /task
 */
export interface TaskRequestBuilder extends BaseRequestBuilder<TaskRequestBuilder> {
    /**
     * The run property
     */
    get run(): RunRequestBuilder;
    /**
     * Gets an item from the ApiSdk.task.item collection
     * @param id Unique identifier of the item
     * @returns {ItemRequestBuilder}
     */
     byId(id: string) : ItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TaskRequestBuilderUriTemplate = "{+baseurl}/task";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TaskRequestBuilderNavigationMetadata: Record<Exclude<keyof TaskRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        navigationMetadata: ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["%2Did"],
    },
    run: {
        requestsMetadata: RunRequestBuilderRequestsMetadata,
        navigationMetadata: RunRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
