/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTaskFromDiscriminatorValue, type Task } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /activity/queue
 */
export interface QueueRequestBuilder extends BaseRequestBuilder<QueueRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Task[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Task[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueueRequestBuilderUriTemplate = "{+baseurl}/activity/queue";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueueRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QueueRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTaskFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
