/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMostPopularFormatDtoFromDiscriminatorValue, type MostPopularFormatDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /commands/formats
 */
export interface FormatsRequestBuilder extends BaseRequestBuilder<FormatsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MostPopularFormatDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MostPopularFormatDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FormatsRequestBuilderUriTemplate = "{+baseurl}/commands/formats";
/**
 * Metadata for all the requests in the request builder.
 */
export const FormatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FormatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMostPopularFormatDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
